### PR TITLE
typo in image type

### PR DESCRIPTION
**Pull request by imcotton**

### CODE REVIEW

**Comment by pjpimentel** [comment]
@imcotton thanks! It has been deployed to **beta** and now i'm deploying to **latest**!

**Comment by imcotton** [comment]
Hi, thanks for taken the PR, a few of questions following:

- should new PR construct against the `dev` branch instead of `master`?
- currently the `typescript` been seated as `dependencies` in **pkg**, shouldn't be in `devDependencies` instead?
- noticed the jasmine specs still failing on latest `master` branch, is it known issue?

**Comment by pjpimentel** [comment]
> Hi, thanks for taken the PR, a few of questions following:
> 
> * should new PR construct against the `dev` branch instead of `master`?
> * currently the `typescript` being set as `dependencies` in **pkg**, shouldn't be in `devDependencies` instead?
> * noticed the jasmine specs still failing on latest `master` branch, is it known issue?

@imcotton 

- Now dev is behind master; but, yes, new features from dev and hot bug fixes from master/beta
- yeah! we should move it there to reduce pkg size
  - After we move it to the right place, we need check if the pipeline still working
- whats exactly is faling? the last [build](https://travis-ci.org/pjpimentel/dots/jobs/438135517) was ok

**Comment by imcotton** [comment]
Oh, I was testing out specs by `npm run test:unit` locally, turns out several test cases require environment variables preset beforehand (`DO_READ_TOKEN`, `DO_WRITE_TOKEN`), so it's more like **e2e** specs aginese DO's api gateway, this way it's fine I think.

**Comment by imcotton** [comment]
About branching, sorry I should have meant `beta` here, so which one should PR goes, `dev` or `beta`?

**Comment by pjpimentel** [comment]
> Oh, I was testing out specs by `npm run test:unit` locally, turns out several test cases require environment variables preset beforehand (`DO_READ_TOKEN`, `DO_WRITE_TOKEN`), so it's more like **e2e** specs against DO's api gateway, this way it's fine I think.

Yes, the test need valid DO API tokens to run successfully.

**Comment by pjpimentel** [comment]
> Hi, thanks for taken the PR, a few of questions following:
> 
> * should new PR construct against the `dev` branch instead of `master`?
**> * currently the `typescript` being set as `dependencies` in **pkg**, shouldn't be in `devDependencies` instead? 
@imcotton version 2.6.0 fix this**
> * noticed the jasmine specs still failing on latest `master` branch, is it known issue?

**Pull request merged**
